#!/usr/bin/env bash
set -e
source $(dirname $0)/scripts/readlinkdashf.sh

version=$(grep -F "VERSION = " settings.go | cut -d\" -f2)

BASEDIR=$(readlinkdashf $(dirname $0))
BINDIR=${BASEDIR}/bin

if [ $PWD != $BASEDIR ]; then
	cd $BASEDIR
fi

ORG_PATH="github.com/fm0l"
REPO_PATH="${ORG_PATH}/goexpose"

mkdir -p ${BINDIR}

VERSION=${STOLON_VERSION:-$(${BASEDIR}/scripts/git-version.sh)}
LD_FLAGS="-s -X ${REPO_PATH}/cmd.Version=$VERSION"

use_go_install=

go_root_dir=$(go env GOROOT)
go_host_os=$(go env GOHOSTOS)
go_host_arch=$(go env GOHOSTARCH)
cgodisabled_pkg_dir=${go_root_dir}/pkg/${go_host_os}_${go_host_arch}_cgo

if [ -e ${cgodisabled_pkg_dir} ]; then
	use_go_install=1
fi

if [ -w ${go_root_dir}/pkg ]; then
	use_go_install=1
fi

CGO_ENABLED=0 go build -installsuffix cgo -ldflags "$LD_FLAGS" -o ${BINDIR}/goexpose-linux-amd64-$version ./cmd/goexpose

